name: First Workflow 
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest 
    steps:
      - name: Pring Greeting
        run: |
            echo "Hello World!"
            echo "How are you?"
      - name: Pring Goodby
        run: echo "By!"
